export const errorCodes = {
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_EXPIRED_TOKEN: "AUTH_EXPIRED_TOKEN",
  AUTH_MISSING_TOKEN: "AUTH_MISSING_TOKEN",
  AUTH_INACTIVE_TOKEN: "AUTH_INACTIVE_TOKEN",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_USER_NOT_VERIFIED: "AUTH_USER_NOT_VERIFIED",
  VALIDATION_SCHEMA_FAILED: "VALIDATION_SCHEMA_FAILED",
  VALIDATION_PAYLOAD_INVALID: "VALIDATION_PAYLOAD_INVALID",
  INVALID_UPDATE_PAYLOAD: "INVALID_UPDATE_PAYLOAD",
  USER_CONFLICT: "USER_CONFLICT",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_CREATE_FAILED: "USER_CREATE_FAILED",
  USER_RETRIEVE_FAILED: "USER_RETRIEVE_FAILED",
  USER_UPDATE_FAILED: "USER_UPDATE_FAILED",
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",
  SYSTEM_UNEXPECTED: "SYSTEM_UNEXPECTED",
  SYSTEM_TOKEN_VALIDATION_FAILED: "SYSTEM_TOKEN_VALIDATION_FAILED",
} as const;

export type ErrorCode = (typeof errorCodes)[keyof typeof errorCodes];
